-- Migration 0005 — populate topic_relations from the comprehensive link pass (Milestone 6, ADR 0005)
--
-- 100 human-confirmed, source-argued relations from the all-285-topics link pass. Each candidate
-- was argued by a Sonnet agent against the infocouncil source documents (Milestone 6 verify pass).
--
-- NO merges are applied here. Every merge candidate was either rejected on source review or routed
-- to the ingest data-quality investigation, because each had a wrong/fabricated item number in D1:
--   Robyn Webster   — item 30 on C_19052026 is a Marion St notice of motion, not the sports centre
--   Centenary Park  — item 50 does not exist (the agenda ends at item 40)
--   Renwick St fire — June item 25 is the 29 Damun (Camperdown Park) playground tender, not the fire matter
--   Balmain/Wran    — May 'Wran Square plaza' is stored as item 22, but item 22 is 'Supporting Visual
--                     Artists and Writers'; the real plaza item is item 8. The May decision + its 5
--                     images may belong to the wrong item, so the merge is unsafe until re-ingested.
--   Investment      — 'Investment report' mixes a property report (Feb item 17) with cash reports; needs a split.
--
-- Reclassifications from the raw candidate set, after source verification:
--   Australia St parklets  : merge      -> parent-child (Council resolution over LTF traffic approval)
--   Curtis/Darling crossing: supersedes -> related (two different crossings, DP 10313 vs 10390)
--   Renwick St fire        : supersedes -> dropped (data error, see above)

INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-accessible-parklets-australia-street-newtown', 'topic-temporary-parklets-australia-st', 'parent-child', 'Council resolution (parent) over LTF traffic approval (child) — same Australia St parklets', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-curtis-road-darling-street-crossing-balmain', 'topic-darling-st-curtis-rd-raised-crossing-and-roundabou', 'related', 'Same Curtis/Darling intersection, two different crossings (DP 10313 vs 10390) — not supersedes', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-old-canterbury-rd-edward-st-traffic-signals', 'topic-safety-measures-for-greenway-impact-weston-street-', 'related', 'Old Canterbury Rd & Edward St traffic signals ~ Safety measures for GreenWay impact, Weston Street, Dulwich Hill', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-safety-measures-for-greenway-impact-weston-street-', 'topic-weston-street-dulwich-hill-traffic-calming', 'related', 'Safety measures for GreenWay impact, Weston Street, Dulwich Hill ~ Weston Street Dulwich Hill traffic calming', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-charlotte-street-staircase-improvements', 'topic-victoria-road-repair', 'related', 'Charlotte Street staircase improvements ~ Victoria Road repair', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-fishers-reserve-palace-continuous-footpath', 'topic-terminus-palace-st-raised-crossing', 'related', 'Fishers Reserve & Palace continuous footpath ~ Terminus & Palace St raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-resident-parking-scheme-leichhardt-west-stage-2-an', 'topic-resident-parking-scheme-lords-rd-davies-st-leichha', 'related', 'Resident parking scheme — Leichhardt West Stage 2 and 3 ~ Resident parking scheme, Lords Rd & Davies St, Leichhardt', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-christmas-2026-decorations-and-light-up-fest', 'topic-christmas-decorations-expansion', 'related', 'Christmas 2026 decorations and Light Up Fest ~ Christmas decorations expansion', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-christmas-2026-decorations-and-light-up-fest', 'topic-christmas-in-inner-west', 'related', 'Christmas 2026 decorations and Light Up Fest ~ Christmas in Inner West', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-christmas-2026-decorations-and-light-up-fest', 'topic-christmas-festivity-initiatives-and-light-up-compe', 'related', 'Christmas 2026 decorations and Light Up Fest ~ Christmas festivity initiatives and Light Up competition', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-dive-in-cinema-and-live-music-aquatic-centre-activ', 'topic-dive-in-movies-at-aquatic-centres', 'related', 'Dive-in cinema and live music — aquatic centre activation ~ Dive-in movies at aquatic centres', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-dive-in-cinema-and-live-music-events-at-aquatic-ce', 'topic-dive-in-movies-at-aquatic-centres', 'related', 'Dive-in cinema and live music events at aquatic centres ~ Dive-in movies at aquatic centres', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-dive-in-cinema-and-summer-music-sessions-at-aquati', 'topic-dive-in-movies-at-aquatic-centres', 'related', 'Dive-in cinema and summer music sessions at aquatic centres ~ Dive-in movies at aquatic centres', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-halloween-competition-and-road-safety-enhancements', 'topic-halloween-promotion-and-safety-initiatives', 'related', 'Halloween competition and road safety enhancements ~ Halloween promotion and safety initiatives', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-italian-festa-road-closures-norton-st', 'topic-norton-st-road-closure-italian-festa', 'related', 'Italian Festa road closures, Norton St ~ Norton St road closure, Italian Festa', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-fogo-food-waste-service-expansion', 'topic-fogo-service-expansion-to-multi-unit-dwellings', 'related', 'FOGO food waste service expansion ~ FOGO service expansion to multi-unit dwellings', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-return-and-earn-container-collection-at-council-ve', 'topic-return-and-earn-support', 'related', 'Return and Earn container collection at council venues ~ Return and Earn support', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-defence-of-democratic-rights-and-peaceful-protest', 'topic-democratic-rights-and-protest-policing', 'related', 'Defence of democratic rights and peaceful protest ~ Democratic rights and protest policing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-nuclear-weapons-treaty-endorsement', 'topic-treaty-on-prohibition-of-nuclear-weapons-support', 'related', 'Nuclear weapons treaty endorsement ~ Treaty on Prohibition of Nuclear Weapons support', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-king-street-crawl-music-festival', 'topic-king-street-special-entertainment-precinct', 'related', 'King Street Crawl music festival ~ King Street Special Entertainment Precinct', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-king-street-entertainment-precinct-coordination-wi', 'topic-king-street-special-entertainment-precinct', 'related', 'King Street entertainment precinct coordination with City of Sydney ~ King Street Special Entertainment Precinct', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-our-fairer-future-stage-2-parramatta-road-rezoning', 'topic-our-fairer-future-zoning-progress', 'related', 'Our Fairer Future Stage 2, Parramatta Road rezoning ~ Our Fairer Future zoning progress', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-community-recycling-centres-operation-and-accessib', 'topic-community-recycling-centres-review', 'related', 'Community Recycling Centres operation and accessibility ~ Community recycling centres review', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-metro-activation-plan-marrickville-and-dulwich-hil', 'topic-metro-station-activations-plan', 'related', 'Metro activation plan — Marrickville and Dulwich Hill stations ~ Metro station activations plan', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-metro-opening-celebration-sydenham-marrickville-du', 'topic-metro-station-activations-plan', 'related', 'Metro opening celebration — Sydenham, Marrickville, Dulwich Hill ~ Metro station activations plan', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-lgbtq-business-support-program', 'topic-lgbtq-businesses-and-venues-support', 'related', 'LGBTQ+ business support program ~ LGBTQ+ businesses and venues support', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-seniors-morning-tea-expansion', 'topic-seniors-morning-teas', 'related', 'Seniors Morning Tea expansion ~ Seniors morning teas', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-local-transport-forum-recommendations', 'related', 'Local transport forum — raised crossings and cycleways ~ Local Transport Forum recommendations', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-local-transport-forum-raised-crossings-and-cyclewa', 'related', 'Local Transport Forum May 2026 ~ Local transport forum — raised crossings and cycleways', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-design-excellence-lep-amendment', 'topic-design-excellence-planning-rules', 'related', 'Design Excellence LEP amendment ~ Design excellence planning rules', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-artist-and-writer-affordable-workspace-support', 'topic-creative-spaces-for-artists', 'related', 'Artist and writer affordable workspace support ~ Creative spaces for artists', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-40km-h-speed-limits', 'topic-speed-limit-reduction-to-40km-h', 'related', '40km/h speed limits ~ Speed limit reduction to 40km/h', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-speed-limit-reduction-haberfield-rozelle-ashfield', 'topic-speed-limit-reduction-to-40km-h', 'related', 'Speed limit reduction, Haberfield, Rozelle & Ashfield ~ Speed limit reduction to 40km/h', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-extended-pool-hours-during-lpac-renovation', 'topic-leichhardt-aquatic-centre-stage-2', 'related', 'Extended pool hours during LPAC renovation ~ Leichhardt Aquatic Centre Stage 2', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-illawarra-road-pipeline-hill-thornley-streets', 'topic-south-marrickville-flood-study', 'related', 'Illawarra Road pipeline — Hill & Thornley Streets ~ South Marrickville flood study', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-dulwich-hill-village-masterplan', 'topic-south-dulwich-hill-traffic-review', 'related', 'Dulwich Hill Village Masterplan ~ South Dulwich Hill traffic review', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-old-canterbury-rd-edward-st-traffic-signals', 'topic-weston-street-dulwich-hill-traffic-calming', 'related', 'Old Canterbury Rd & Edward St traffic signals ~ Weston Street Dulwich Hill traffic calming', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-curtis-road-darling-street-crossing-balmain', 'topic-speed-cushion-and-no-stopping-curtis-road-balmain', 'related', 'Curtis Road & Darling Street crossing, Balmain ~ Speed cushion and no stopping — Curtis Road, Balmain', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-darling-st-curtis-rd-raised-crossing-and-roundabou', 'topic-speed-cushion-and-no-stopping-curtis-road-balmain', 'related', 'Darling St & Curtis Rd raised crossing and roundabout ~ Speed cushion and no stopping — Curtis Road, Balmain', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-lackey-street-summer-hill-event-ready-space', 'topic-summer-hill-social-event-road-closure', 'related', 'Lackey Street Summer Hill event-ready space ~ Summer Hill Social event road closure', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-drynan-street-prospect-road-crossing-summer-hill', 'topic-prospect-rd-between-norton-smith-raised-crossing', 'related', 'Drynan Street & Prospect Road crossing, Summer Hill ~ Prospect Rd between Norton & Smith raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-hurlstone-ave-from-prospect-rd-no-left-turn-ban', 'topic-prospect-rd-between-norton-smith-raised-crossing', 'related', 'Hurlstone Ave from Prospect Rd No Left Turn ban ~ Prospect Rd between Norton & Smith raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-drynan-street-prospect-road-crossing-summer-hill', 'topic-hurlstone-ave-from-prospect-rd-no-left-turn-ban', 'related', 'Drynan Street & Prospect Road crossing, Summer Hill ~ Hurlstone Ave from Prospect Rd No Left Turn ban', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-enmore-walk-of-fame', 'topic-king-street-crawl-music-festival', 'related', 'Enmore Walk of Fame ~ King Street Crawl music festival', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-king-street-crawl-music-festival', 'topic-king-street-entertainment-precinct-coordination-wi', 'related', 'King Street Crawl music festival ~ King Street entertainment precinct coordination with City of Sydney', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-robert-queen-road-safety-improvements', 'topic-traffic-safety-study-queen-armstrong-harland-and-h', 'related', 'Robert & Queen road safety improvements ~ Traffic safety study — Queen, Armstrong, Harland and Hardy Streets, Ashfield', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-robert-queen-road-safety-improvements', 'topic-victoria-street-robert-street-crossing-ashfield', 'related', 'Robert & Queen road safety improvements ~ Victoria Street & Robert Street crossing, Ashfield', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-wells-st-at-commodore-john-sts-raised-thresholds', 'topic-wells-st-king-st-raised-footpath', 'related', 'Wells St at Commodore & John Sts raised thresholds ~ Wells St & King St raised footpath', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-car-share-parking-fees', 'topic-seniors-workshops-on-vehicle-ownership-transition', 'related', 'Car share parking fees ~ Seniors workshops on vehicle ownership transition', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-audit-committee-governance-and-risk-monitoring', 'topic-audit-risk-and-improvement-committee-minutes', 'related', 'Audit committee governance and risk monitoring ~ Audit Risk and Improvement Committee minutes', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-pecuniary-interest-disclosure', 'topic-pecuniary-interest-returns', 'related', 'Pecuniary interest disclosure ~ Pecuniary interest returns', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-centenary-park-cricket-nets-upgrade', 'topic-centenary-park-sports-ground-upgrade', 'related', 'Centenary Park cricket nets upgrade ~ Centenary Park sports ground upgrade', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-fire-and-rescue-nsw-safety-inspections', 'topic-fire-safety-reports', 'related', 'Fire and Rescue NSW safety inspections ~ Fire safety reports', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-flood-management-advisory-committee-recommendation', 'topic-south-marrickville-flood-study', 'related', 'Flood Management Advisory Committee recommendations ~ South Marrickville flood study', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-flood-management-advisory-committee-recommendation', 'topic-illawarra-road-pipeline-hill-thornley-streets', 'related', 'Flood Management Advisory Committee recommendations ~ Illawarra Road pipeline — Hill & Thornley Streets', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-flood-management-advisory-committee-recommendation', 'topic-osgood-avenue-stormwater-drainage', 'related', 'Flood Management Advisory Committee recommendations ~ Osgood Avenue stormwater drainage', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-murray-st-raised-crossing-with-islands-marrickvill', 'topic-smidmore-st-edinburgh-rd-no-stopping-zone', 'related', 'Murray St raised crossing with islands, Marrickville ~ Smidmore St & Edinburgh Rd no stopping zone', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-shaw-st-belgrave-st-stop-control-and-kerb-extensio', 'topic-shaw-st-north-of-oxford-st-raised-crossing', 'related', 'Shaw St & Belgrave St STOP control and kerb extensions ~ Shaw St north of Oxford St raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-arthur-st-illawarra-rd-raised-footpath', 'parent-child', 'Local Transport Forum recommendations ~ Arthur St & Illawarra Rd raised footpath', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-college-street-bicycles-excepted-one-way', 'parent-child', 'Local Transport Forum recommendations ~ College Street bicycles excepted one-way', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-fishers-reserve-palace-continuous-footpath', 'parent-child', 'Local Transport Forum recommendations ~ Fishers Reserve & Palace continuous footpath', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-hardie-ave-raised-crossing', 'parent-child', 'Local Transport Forum recommendations ~ Hardie Ave raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-kingston-deakin-pedestrian-refuge-islands', 'parent-child', 'Local Transport Forum recommendations ~ Kingston & Deakin pedestrian refuge islands', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-robert-queen-road-safety-improvements', 'parent-child', 'Local Transport Forum recommendations ~ Robert & Queen road safety improvements', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-terminus-palace-st-raised-crossing', 'parent-child', 'Local Transport Forum recommendations ~ Terminus & Palace St raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-thornley-st-cary-st-kerb-extension', 'parent-child', 'Local Transport Forum recommendations ~ Thornley St & Cary St kerb extension', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-wardell-road-marrickville-raised-crossing', 'parent-child', 'Local Transport Forum recommendations ~ Wardell Road Marrickville raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-wells-st-king-st-raised-footpath', 'parent-child', 'Local Transport Forum recommendations ~ Wells St & King St raised footpath', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-no-parking-restriction-laneway', 'parent-child', 'Local Transport Forum recommendations ~ No parking restriction, laneway', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-goget-car-share-spaces-inner-west', 'parent-child', 'Local Transport Forum recommendations ~ GoGet car share spaces, Inner West', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-dickson-king-st-refuge-island', 'parent-child', 'Local Transport Forum recommendations ~ Dickson & King St refuge island', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-traffic-calming-works-near-bunnings-tempe', 'parent-child', 'Local Transport Forum recommendations ~ Traffic calming works near Bunnings Tempe', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-st-peters-station-parking-study', 'parent-child', 'Local Transport Forum recommendations ~ St Peters Station parking study', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-recommendations', 'topic-resident-parking-scheme-mackey-park-precinct-marri', 'parent-child', 'Local Transport Forum recommendations ~ Resident parking scheme, Mackey Park precinct, Marrickville', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-darling-st-curtis-rd-raised-crossing-and-roundabou', 'parent-child', 'Local Transport Forum May 2026 ~ Darling St & Curtis Rd raised crossing and roundabout', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-nelson-lane-no-parking-zone-extension', 'parent-child', 'Local Transport Forum May 2026 ~ Nelson Lane no parking zone extension', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-warburton-st-illawarra-rd-kerb-blister', 'parent-child', 'Local Transport Forum May 2026 ~ Warburton St & Illawarra Rd kerb blister', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-illawarra-rd-wharf-st-crossing', 'parent-child', 'Local Transport Forum May 2026 ~ Illawarra Rd & Wharf St crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-illawarra-rd-grove-st-raised-crossing', 'parent-child', 'Local Transport Forum May 2026 ~ Illawarra Rd & Grove St raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-smidmore-st-edinburgh-rd-no-stopping-zone', 'parent-child', 'Local Transport Forum May 2026 ~ Smidmore St & Edinburgh Rd no stopping zone', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-nowranie-st-smith-st-kerb-extensions', 'parent-child', 'Local Transport Forum May 2026 ~ Nowranie St & Smith St kerb extensions', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-hardy-st-mount-st-raised-crossing-and-kerb-extensi', 'parent-child', 'Local Transport Forum May 2026 ~ Hardy St & Mount St raised crossing and kerb extensions', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-allen-st-raised-crossing', 'parent-child', 'Local Transport Forum May 2026 ~ Allen St raised crossing', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-resident-parking-scheme-mackey-park-precinct-marri', 'parent-child', 'Local Transport Forum May 2026 ~ Resident parking scheme, Mackey Park precinct, Marrickville', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-no-parking-zone-little-brighton-st-petersham', 'parent-child', 'Local Transport Forum May 2026 ~ No parking zone, Little Brighton St, Petersham', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-may-2026', 'topic-resident-parking-scheme-lords-rd-davies-st-leichha', 'parent-child', 'Local Transport Forum May 2026 ~ Resident parking scheme, Lords Rd & Davies St, Leichhardt', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-marrickville-rd-sydney-st-crossing-and-cycleway', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ Marrickville Rd & Sydney St crossing and cycleway', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-seaview-st-yeo-ave-raised-threshold', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ Seaview St & Yeo Ave raised threshold', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-mcrae-st-livingstone-rd-kerb-blister-and-extension', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ McRae St & Livingstone Rd kerb blister and extension', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-lilyfield-road-cycleway', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ Lilyfield Road cycleway', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-mcgill-st-old-canterbury-rd-kerb-extensions', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ McGill St & Old Canterbury Rd kerb extensions', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-norton-st-lapish-ave-zebra-crossing-with-kerb-exte', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ Norton St & Lapish Ave zebra crossing with kerb extension', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-local-transport-forum-raised-crossings-and-cyclewa', 'topic-temporary-parklets-australia-st', 'parent-child', 'Local transport forum — raised crossings and cycleways ~ Temporary parklets, Australia St', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-car-share-parking-fees', 'topic-goget-car-share-spaces-inner-west', 'parent-child', 'Car share parking fees ~ GoGet car share spaces, Inner West', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-car-share-parking-fees', 'topic-flexicar-car-share-parking-spaces', 'parent-child', 'Car share parking fees ~ Flexicar car share parking spaces', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-south-marrickville-flood-study', 'topic-osgood-avenue-stormwater-drainage', 'parent-child', 'South Marrickville flood study ~ Osgood Avenue stormwater drainage', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-business-roundtable-action-plans', 'topic-crystal-street-business-improvements-petersham', 'parent-child', 'Business Roundtable Action Plans ~ Crystal Street business improvements, Petersham', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-public-ev-chargers-expansion-plan', 'topic-ev-kerbside-charging-locations', 'parent-child', 'Public EV chargers expansion plan ~ EV kerbside charging locations', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-fire-safety-reports', 'topic-fire-safety-orders-renwick-st-leichhardt', 'parent-child', 'Fire safety reports ~ Fire safety orders — Renwick St, Leichhardt', 'human', '2026-06-13');
INSERT OR IGNORE INTO topic_relations (topic_a, topic_b, kind, note, source, created_at) VALUES ('topic-parklets-and-on-road-dining', 'topic-accessible-parklets-australia-street-newtown', 'parent-child', 'Parklets and on-road dining ~ Accessible parklets, Australia Street Newtown', 'human', '2026-06-13');
